# Generated by Django 5.1.15 on 2026-05-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OIDCConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_name", models.CharField(max_length=255, unique=True)),
                ("client_id", models.CharField(max_length=255)),
                ("_client_secret", models.TextField(db_column="client_secret")),
                (
                    "discovery_url",
                    models.URLField(
                        help_text="OIDC Provider Discovery URL (/.well-known/openid-configuration)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
