# Generated by Django 5.1.15 on 2026-06-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_create_rbac_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_service_account",
            field=models.BooleanField(default=False),
        ),
    ]
