# Generated by Django 5.1.15 on 2026-06-02 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinical", "0014_remove_synctask_hierarchy_level_and_more"),
        ("events", "0002_alter_deliveryattempt_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliveryattempt",
            name="retry_count",
        ),
        migrations.AddField(
            model_name="deliveryattempt",
            name="response_code",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="outboundevent",
            name="record_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="clinical.recordrevision",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="clinical.site",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="study",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="clinical.study",
            ),
        ),
    ]
