# Generated by Django 5.1.15 on 2026-06-23 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clinical", "0018_alter_syncjob_file_path"),
    ]

    operations = [
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "imednet_id",
                    models.CharField(
                        db_index=True,
                        help_text="External iMednet ID (formId).",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "form_key",
                    models.CharField(
                        db_index=True,
                        help_text="External form key (formKey).",
                        max_length=100,
                    ),
                ),
                ("form_name", models.CharField(max_length=255)),
                ("form_type", models.CharField(max_length=100)),
                ("revision", models.IntegerField()),
                ("embedded_log", models.BooleanField(default=False)),
                ("enforce_ownership", models.BooleanField(default=False)),
                ("user_agreement", models.BooleanField(default=False)),
                ("subject_record_report", models.BooleanField(default=False)),
                ("unscheduled_visit", models.BooleanField(default=False)),
                ("other_forms", models.BooleanField(default=False)),
                ("epro_form", models.BooleanField(default=False)),
                ("allow_copy", models.BooleanField(default=False)),
                (
                    "disabled",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the form is disabled or soft-deleted in iMednet.",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        help_text="The study this form belongs to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="imednet_forms",
                        to="clinical.study",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
