# Generated by Django 5.1.15 on 2026-06-23 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinical", "0018_alter_syncjob_file_path"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "imednet_id",
                    models.CharField(
                        db_index=True,
                        help_text="External iMednet ID (userId).",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "login",
                    models.CharField(
                        db_index=True,
                        help_text="User login name.",
                        max_length=150,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=255)),
                (
                    "user_active_in_study",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates if the user is active in the study.",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        help_text="The study this user belongs to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="imednet_users",
                        to="clinical.study",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_name", models.CharField(max_length=255)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="core.user",
                    ),
                ),
            ],
        ),
    ]
