# Generated by Django 5.1.15 on 2026-06-23 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0018_alter_syncjob_file_path"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "imednet_id",
                    models.CharField(
                        db_index=True,
                        help_text="External iMednet ID (jobId).",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        db_index=True,
                        help_text="External batch ID (batchId).",
                        max_length=255,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        help_text="The current state of the job.", max_length=100
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        help_text="Date the job was created in iMednet."
                    ),
                ),
                (
                    "date_started",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date the job started in iMednet.",
                        null=True,
                    ),
                ),
                (
                    "date_finished",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date the job finished in iMednet.",
                        null=True,
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        help_text="The study this job belongs to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="imednet_jobs",
                        to="clinical.study",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
