# Generated by Django 5.1.15 on 2026-06-23 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0018_alter_syncjob_file_path"),
        ("core", "0002_user_userrole"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecordRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "imednet_id",
                    models.CharField(
                        db_index=True,
                        help_text="External iMednet ID (recordRevisionId).",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "imednet_record_id",
                    models.IntegerField(help_text="External record ID (recordId)."),
                ),
                (
                    "record_oid",
                    models.CharField(help_text="External record OID.", max_length=255),
                ),
                (
                    "record_revision",
                    models.IntegerField(help_text="Record revision number."),
                ),
                (
                    "data_revision",
                    models.IntegerField(help_text="Data revision number."),
                ),
                (
                    "record_status",
                    models.CharField(help_text="Status of the record.", max_length=255),
                ),
                (
                    "imednet_subject_id",
                    models.IntegerField(help_text="External subject ID."),
                ),
                (
                    "subject_oid",
                    models.CharField(help_text="External subject OID.", max_length=255),
                ),
                (
                    "subject_key",
                    models.CharField(
                        db_index=True, help_text="External subject key.", max_length=100
                    ),
                ),
                ("site_id", models.IntegerField(help_text="External site ID.")),
                (
                    "form_key",
                    models.CharField(
                        db_index=True, help_text="External form key.", max_length=100
                    ),
                ),
                (
                    "interval_id",
                    models.IntegerField(
                        blank=True, help_text="External interval ID.", null=True
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        help_text="Role associated with the revision.", max_length=255
                    ),
                ),
                (
                    "user_raw",
                    models.CharField(help_text="Raw user information.", max_length=255),
                ),
                (
                    "reason_for_change",
                    models.TextField(blank=True, help_text="Reason for change."),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the revision is deleted in iMednet.",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        help_text="The record this revision belongs to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="imednet_record_revisions",
                        to="clinical.record",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        help_text="The study this record revision belongs to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="imednet_record_revisions",
                        to="clinical.study",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="The subject this record revision belongs to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="imednet_record_revisions",
                        to="clinical.subject",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        help_text="The user profile associated with this revision.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="record_revisions",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
