# Generated by Django 5.1.15 on 2026-06-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_recordrevision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recordrevision",
            name="role",
            field=models.CharField(
                blank=True,
                help_text="Role associated with the revision.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="recordrevision",
            name="user_raw",
            field=models.CharField(blank=True, help_text="Raw user information.", max_length=255),
        ),
    ]
