# Generated by Django 5.1.15 on 2026-06-23 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinical", "0018_alter_syncjob_file_path"),
        ("core", "0005_alter_recordrevision_role_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "imednet_id",
                    models.CharField(
                        db_index=True,
                        help_text="External iMednet ID (intervalId).",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("interval_name", models.CharField(max_length=255)),
                ("interval_description", models.TextField(blank=True)),
                ("interval_sequence", models.IntegerField()),
                ("interval_group_id", models.IntegerField()),
                ("interval_group_name", models.CharField(max_length=255)),
                ("timeline", models.CharField(max_length=100)),
                (
                    "defined_using_interval",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "window_calculation_form",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "window_calculation_date",
                    models.CharField(blank=True, max_length=255),
                ),
                ("actual_date_form", models.CharField(blank=True, max_length=255)),
                ("actual_date", models.CharField(blank=True, max_length=255)),
                ("due_date_will_be_in", models.IntegerField(blank=True, null=True)),
                ("negative_slack", models.IntegerField(blank=True, null=True)),
                ("positive_slack", models.IntegerField(blank=True, null=True)),
                ("epro_grace_period", models.IntegerField(blank=True, null=True)),
                (
                    "disabled",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the interval is disabled or soft-deleted in iMednet.",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        help_text="The study this interval belongs to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="imednet_intervals",
                        to="clinical.study",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IntervalForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.form"),
                ),
                (
                    "interval",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.interval"),
                ),
            ],
            options={
                "unique_together": {("interval", "form")},
            },
        ),
        migrations.AddField(
            model_name="interval",
            name="forms",
            field=models.ManyToManyField(related_name="intervals", through="core.IntervalForm", to="core.form"),
        ),
    ]
