# Generated by Django 5.1.15 on 2026-06-23 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0019_syncjob_contains_phi_synctask_contains_phi"),
        ("core", "0006_interval_intervalform_interval_forms"),
    ]

    operations = [
        migrations.CreateModel(
            name="Variable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "form_key_raw",
                    models.CharField(
                        blank=True,
                        help_text="Raw form ID from iMednet, used for error tracking if form lookup fails.",
                        max_length=255,
                    ),
                ),
                (
                    "imednet_id",
                    models.CharField(
                        db_index=True,
                        help_text="External iMednet ID (variableId).",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("variable_type", models.CharField(max_length=100)),
                ("variable_name", models.CharField(max_length=255)),
                ("sequence", models.IntegerField()),
                ("revision", models.IntegerField()),
                ("disabled", models.BooleanField(default=False)),
                (
                    "variable_oid",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("deleted", models.BooleanField(default=False)),
                ("label", models.TextField(blank=True)),
                ("blinded", models.BooleanField(default=False)),
                (
                    "form",
                    models.ForeignKey(
                        blank=True,
                        help_text="The form this variable belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="variables",
                        to="core.form",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        help_text="The study this variable belongs to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="imednet_variables",
                        to="clinical.study",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
