# Generated by Django 5.1.15 on 2026-06-23 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinical", "0019_syncjob_contains_phi_synctask_contains_phi"),
        ("core", "0007_variable"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site_name_raw",
                    models.CharField(
                        blank=True,
                        help_text="Raw site name from iMednet, used for error tracking if site lookup fails.",
                        max_length=255,
                    ),
                ),
                (
                    "imednet_id",
                    models.CharField(
                        db_index=True,
                        help_text="External iMednet ID (subjectId).",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "subject_oid",
                    models.CharField(help_text="External subject OID.", max_length=255),
                ),
                (
                    "subject_key",
                    models.CharField(
                        db_index=True,
                        help_text="External subject key.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "subject_status",
                    models.CharField(help_text="Status of the subject.", max_length=100),
                ),
                (
                    "enrollment_start_date",
                    models.DateTimeField(blank=True, help_text="Enrollment start date.", null=True),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the subject is deleted in iMednet.",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        help_text="The site this subject belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="imednet_subjects",
                        to="clinical.site",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        help_text="The study this subject belongs to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="imednet_subjects",
                        to="clinical.study",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SubjectKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=255)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keywords",
                        to="core.subject",
                    ),
                ),
            ],
        ),
    ]
