# Generated by Django 5.1.15 on 2026-06-23 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinical", "0019_syncjob_contains_phi_synctask_contains_phi"),
        ("core", "0008_subject_subjectkeyword"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "imednet_id",
                    models.CharField(
                        db_index=True,
                        help_text="External iMednet ID (visitId).",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("interval_name_raw", models.CharField(max_length=255)),
                ("subject_key_raw", models.CharField(max_length=100)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("visit_date", models.DateField(blank=True, null=True)),
                ("visit_date_form", models.CharField(blank=True, max_length=255)),
                ("deleted", models.BooleanField(default=False)),
                ("visit_date_question", models.CharField(blank=True, max_length=100)),
                (
                    "interval",
                    models.ForeignKey(
                        help_text="The interval this visit belongs to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="imednet_visits",
                        to="core.interval",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        help_text="The study this visit belongs to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="imednet_visits",
                        to="clinical.study",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="The subject this visit belongs to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="imednet_visits",
                        to="core.subject",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
