# Generated by Django 5.1.15 on 2026-06-23 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0020_bufferedorphan_contains_phi"),
        ("core", "0009_visit"),
    ]

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "imednet_id",
                    models.CharField(
                        db_index=True,
                        help_text="External record ID (recordId).",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "record_oid",
                    models.CharField(
                        blank=True, help_text="External record OID.", max_length=255
                    ),
                ),
                (
                    "record_type",
                    models.CharField(help_text="Type of the record.", max_length=100),
                ),
                (
                    "record_status",
                    models.CharField(help_text="Status of the record.", max_length=255),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the record is deleted in iMednet.",
                    ),
                ),
                (
                    "imednet_subject_id",
                    models.IntegerField(help_text="External subject ID (subjectId)."),
                ),
                (
                    "subject_oid",
                    models.CharField(
                        blank=True, help_text="External subject OID.", max_length=255
                    ),
                ),
                (
                    "subject_key",
                    models.CharField(
                        db_index=True, help_text="External subject key.", max_length=100
                    ),
                ),
                (
                    "imednet_visit_id",
                    models.IntegerField(
                        blank=True, help_text="External visit ID (visitId).", null=True
                    ),
                ),
                (
                    "parent_record_id",
                    models.IntegerField(
                        blank=True, help_text="External parent record ID.", null=True
                    ),
                ),
                (
                    "record_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Schema-less record data."
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        help_text="The form this record belongs to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="imednet_records",
                        to="core.form",
                    ),
                ),
                (
                    "interval",
                    models.ForeignKey(
                        help_text="The interval this record belongs to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="imednet_records",
                        to="core.interval",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        help_text="The site this record belongs to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="imednet_records",
                        to="clinical.site",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        help_text="The study this record belongs to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="imednet_records",
                        to="clinical.study",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="The subject this record belongs to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="imednet_records",
                        to="core.subject",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        blank=True,
                        help_text="The visit this record belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="imednet_records",
                        to="core.visit",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RecordKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=255)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keywords",
                        to="core.record",
                    ),
                ),
            ],
        ),
    ]
