# Generated by Django 5.1.15 on 2026-06-23 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinical", "0020_bufferedorphan_contains_phi"),
        ("core", "0010_record_recordkeyword"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "imednet_id",
                    models.CharField(
                        db_index=True,
                        help_text="External iMednet ID (codingId).",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("site_name", models.CharField(max_length=255)),
                ("site_id", models.IntegerField()),
                (
                    "imednet_subject_id",
                    models.IntegerField(help_text="External subject ID (subjectId)."),
                ),
                ("revision", models.IntegerField()),
                (
                    "imednet_record_id",
                    models.IntegerField(help_text="External record ID (recordId)."),
                ),
                ("value", models.TextField()),
                ("code", models.TextField()),
                ("reason", models.TextField(blank=True)),
                ("dictionary_name", models.CharField(db_index=True, max_length=100)),
                ("dictionary_version", models.CharField(max_length=50)),
                ("date_coded", models.DateTimeField()),
                (
                    "subject_key_raw",
                    models.CharField(
                        blank=True,
                        help_text="Raw subject key backup for error tracking.",
                        max_length=100,
                    ),
                ),
                (
                    "variable_raw",
                    models.CharField(
                        blank=True,
                        help_text="Raw variable backup for error tracking.",
                        max_length=255,
                    ),
                ),
                (
                    "coded_by_raw",
                    models.CharField(
                        blank=True,
                        help_text="Raw user backup for error tracking.",
                        max_length=255,
                    ),
                ),
                (
                    "coded_by_user",
                    models.ForeignKey(
                        help_text="The user who performed the coding.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="imednet_codings",
                        to="core.user",
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        help_text="The form this coding belongs to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="imednet_codings",
                        to="core.form",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        help_text="The study this coding belongs to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="imednet_codings",
                        to="clinical.study",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="The subject this coding belongs to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="imednet_codings",
                        to="core.subject",
                    ),
                ),
                (
                    "variable_ref",
                    models.ForeignKey(
                        help_text="The variable reference this coding belongs to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="imednet_codings",
                        to="core.variable",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
