# Generated by Django 5.1.15 on 2026-06-23 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0020_bufferedorphan_contains_phi"),
        ("core", "0011_coding"),
    ]

    operations = [
        migrations.CreateModel(
            name="Query",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "imednet_id",
                    models.CharField(
                        db_index=True,
                        help_text="External iMednet ID (annotationId).",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "imednet_subject_id",
                    models.IntegerField(help_text="External subject ID (subjectId)."),
                ),
                (
                    "subject_oid",
                    models.CharField(
                        help_text="External subject OID (subjectOid).", max_length=255
                    ),
                ),
                (
                    "annotation_type",
                    models.CharField(
                        help_text="Type of annotation (annotationType).", max_length=100
                    ),
                ),
                (
                    "query_type",
                    models.CharField(
                        blank=True,
                        help_text="Specific query type if applicable (type).",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("description", models.TextField(help_text="Query description.")),
                (
                    "imednet_record_id",
                    models.IntegerField(
                        blank=True,
                        help_text="External record ID (recordId).",
                        null=True,
                    ),
                ),
                (
                    "variable_raw",
                    models.CharField(
                        help_text="Raw variable name from iMednet.", max_length=100
                    ),
                ),
                (
                    "subject_key",
                    models.CharField(
                        db_index=True,
                        help_text="External subject key (subjectKey).",
                        max_length=100,
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        blank=True,
                        help_text="The record this query belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="imednet_queries",
                        to="core.record",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        help_text="The study this query belongs to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="imednet_queries",
                        to="clinical.study",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="The subject this query belongs to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="imednet_queries",
                        to="core.subject",
                    ),
                ),
                (
                    "variable_ref",
                    models.ForeignKey(
                        blank=True,
                        help_text="The variable reference this query belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="imednet_queries",
                        to="core.variable",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="QueryComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                (
                    "user_raw",
                    models.CharField(
                        help_text="Raw user information from iMednet.", max_length=255
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        help_text="The date and time the comment was created."
                    ),
                ),
                (
                    "query",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="core.query",
                    ),
                ),
            ],
        ),
    ]
