# Generated by Django 5.1.15 on 2026-06-23 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinical", "0020_bufferedorphan_contains_phi"),
        ("core", "0012_query_querycomment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "imednet_id",
                    models.CharField(
                        db_index=True,
                        help_text="External iMednet ID (jobId).",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        db_index=True,
                        help_text="External batch ID (batchId).",
                        max_length=255,
                    ),
                ),
                ("state", models.CharField(max_length=100)),
                ("date_created", models.DateTimeField()),
                ("date_started", models.DateTimeField(blank=True, null=True)),
                ("date_finished", models.DateTimeField(blank=True, null=True)),
                (
                    "study",
                    models.ForeignKey(
                        help_text="The study this job belongs to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="imednet_jobs",
                        to="clinical.study",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
