# Generated by Django 5.1.15 on 2026-07-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="date_of_birth",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
