# Generated by Django 5.1.15 on 2026-05-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coding",
            name="clinical_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coding",
            name="offset_days",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coding",
            name="source_sequence",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="form",
            name="clinical_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="form",
            name="offset_days",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="form",
            name="source_sequence",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="interval",
            name="clinical_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="interval",
            name="offset_days",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="interval",
            name="source_sequence",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="query",
            name="clinical_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="query",
            name="offset_days",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="query",
            name="source_sequence",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="record",
            name="clinical_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="record",
            name="offset_days",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="record",
            name="source_sequence",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recordrevision",
            name="clinical_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recordrevision",
            name="offset_days",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recordrevision",
            name="source_sequence",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="clinical_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="offset_days",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="source_sequence",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="study",
            name="clinical_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="study",
            name="offset_days",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="study",
            name="source_sequence",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subject",
            name="clinical_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subject",
            name="offset_days",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subject",
            name="source_sequence",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variable",
            name="clinical_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variable",
            name="offset_days",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variable",
            name="source_sequence",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="clinical_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="offset_days",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="source_sequence",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
