# Generated by Django 5.1.15 on 2026-05-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinical", "0002_coding_clinical_timestamp_coding_offset_days_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_successful_pull", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="UNKNOWN", max_length=50)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
