# Generated by Django 5.1.15 on 2026-05-28 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0002_coding_clinical_timestamp_coding_offset_days_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("api_endpoint", models.URLField(blank=True, null=True)),
                (
                    "auth_type",
                    models.CharField(
                        choices=[
                            ("OIDC", "OIDC"),
                            ("API_KEY", "API Key"),
                            ("OAUTH2", "OAuth2"),
                            ("BASIC", "Basic Auth"),
                        ],
                        default="API_KEY",
                        max_length=50,
                    ),
                ),
                ("auth_credentials", models.JSONField(blank=True, default=dict)),
                ("hierarchy_mapping", models.JSONField(blank=True, default=dict)),
                ("schema_mapping", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="coding",
            name="external_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="form",
            name="external_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="interval",
            name="external_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="query",
            name="external_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="record",
            name="external_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="recordrevision",
            name="external_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="site",
            name="external_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="study",
            name="external_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="subject",
            name="external_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="variable",
            name="external_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="visit",
            name="external_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name="coding",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_entities",
                to="clinical.provider",
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_entities",
                to="clinical.provider",
            ),
        ),
        migrations.AddField(
            model_name="interval",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_entities",
                to="clinical.provider",
            ),
        ),
        migrations.AddField(
            model_name="query",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_entities",
                to="clinical.provider",
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_entities",
                to="clinical.provider",
            ),
        ),
        migrations.AddField(
            model_name="recordrevision",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_entities",
                to="clinical.provider",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_entities",
                to="clinical.provider",
            ),
        ),
        migrations.AddField(
            model_name="study",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_entities",
                to="clinical.provider",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_entities",
                to="clinical.provider",
            ),
        ),
        migrations.AddField(
            model_name="variable",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_entities",
                to="clinical.provider",
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_entities",
                to="clinical.provider",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="coding",
            unique_together={("provider", "external_id")},
        ),
        migrations.AlterUniqueTogether(
            name="form",
            unique_together={("provider", "external_id")},
        ),
        migrations.AlterUniqueTogether(
            name="interval",
            unique_together={("provider", "external_id")},
        ),
        migrations.AlterUniqueTogether(
            name="query",
            unique_together={("provider", "external_id")},
        ),
        migrations.AlterUniqueTogether(
            name="record",
            unique_together={("provider", "external_id")},
        ),
        migrations.AlterUniqueTogether(
            name="recordrevision",
            unique_together={("provider", "external_id")},
        ),
        migrations.AlterUniqueTogether(
            name="site",
            unique_together={("provider", "external_id")},
        ),
        migrations.AlterUniqueTogether(
            name="study",
            unique_together={("provider", "external_id")},
        ),
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together={("provider", "external_id")},
        ),
        migrations.AlterUniqueTogether(
            name="variable",
            unique_together={("provider", "external_id")},
        ),
        migrations.AlterUniqueTogether(
            name="visit",
            unique_together={("provider", "external_id")},
        ),
    ]
