# Generated by Django 5.1.15 on 2026-05-28 20:25

from django.db import migrations


def create_legacy_provider(apps, schema_editor):
    Provider = apps.get_model('clinical', 'Provider')
    provider, _ = Provider.objects.get_or_create(name='Legacy/Default')

    models_to_update = [
        'Study', 'Site', 'Subject', 'Form', 'Interval',
        'Variable', 'Visit', 'Record', 'Coding', 'Query', 'RecordRevision'
    ]
    for model_name in models_to_update:
        Model = apps.get_model('clinical', model_name)
        Model.objects.filter(provider__isnull=True).update(provider=provider)


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0003_provider_alter_coding_external_id_and_more"),
    ]

    operations = [
        migrations.RunPython(create_legacy_provider, migrations.RunPython.noop),
    ]
