# Generated by Django 5.1.15 on 2026-05-29 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0008_assign_legacy_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="bufferedorphan",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="clinical.provider",
            ),
        ),
        migrations.AddField(
            model_name="syncjob",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="clinical.provider",
            ),
        ),
    ]
