# Generated by Django 5.1.15 on 2026-05-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinical", "0009_bufferedorphan_provider_syncjob_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="query",
            name="last_sync_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="query",
            name="status",
            field=models.CharField(default="OPEN", max_length=50),
        ),
        migrations.AddField(
            model_name="query",
            name="sync_status",
            field=models.CharField(default="CONFIRMED", max_length=50),
        ),
    ]
