# Generated by Django 5.1.15 on 2026-05-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinical", "0010_query_last_sync_error_query_status_query_sync_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="query",
            name="previous_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
