# Generated by Django 5.1.15 on 2026-05-30 01:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0011_query_previous_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="syncjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("STALLED", "Stalled"),
                    ("CANCELLED", "Cancelled"),
                    ("TIMED_OUT", "Timed Out"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="synctask",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("STALLED", "Stalled"),
                    ("CANCELLED", "Cancelled"),
                    ("TIMED_OUT", "Timed Out"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="SyncEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("status_from", models.CharField(max_length=50)),
                ("status_to", models.CharField(max_length=50)),
                ("message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sync_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinical.syncjob",
                    ),
                ),
                (
                    "sync_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinical.synctask",
                    ),
                ),
            ],
        ),
    ]
