# Generated by Django 5.1.15 on 2026-05-30 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0011_query_previous_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="variable",
            name="cdisc_domain",
            field=models.CharField(default="VS", max_length=10),
        ),
    ]
