# Generated by Django 5.1.15 on 2026-05-30 00:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinical", "0012_exportjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="pii_masking_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
