# Generated by Django 5.1.15 on 2026-05-30 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0012_variable_cdisc_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordrevision",
            name="reason_for_change",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
