# Generated by Django 5.1.15 on 2026-06-02 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0013_study_pii_masking_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bufferedorphan",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="clinical.provider"
            ),
        ),
        migrations.AlterField(
            model_name="coding",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="clinical.provider"
            ),
        ),
        migrations.AlterField(
            model_name="form",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="clinical.provider"
            ),
        ),
        migrations.AlterField(
            model_name="interval",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="clinical.provider"
            ),
        ),
        migrations.AlterField(
            model_name="query",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="clinical.provider"
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="clinical.provider"
            ),
        ),
        migrations.AlterField(
            model_name="recordrevision",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="clinical.provider"
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="clinical.provider"
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="clinical.provider"
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="clinical.provider"
            ),
        ),
        migrations.AlterField(
            model_name="syncjob",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="clinical.provider"
            ),
        ),
        migrations.AlterField(
            model_name="variable",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="clinical.provider"
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="clinical.provider"
            ),
        ),
    ]
