# Generated by Django 5.1.15 on 2026-06-02 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0013_study_pii_masking_enabled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="synctask",
            name="hierarchy_level",
        ),
        migrations.AddField(
            model_name="synctask",
            name="dependencies",
            field=models.ManyToManyField(
                blank=True, related_name="dependents", to="clinical.synctask"
            ),
        ),
    ]
