# Generated by Django 5.1.15 on 2026-06-02 02:04

import logging

import django.db.models.deletion
from django.db import migrations, models

logger = logging.getLogger(__name__)


def backfill_null_providers(apps, schema_editor):
    """Backfill NULL provider fields before altering to NOT NULL."""
    Provider = apps.get_model('clinical', 'Provider')

    # Get a default provider to assign to existing NULL records
    default_provider = Provider.objects.first()

    if not default_provider:
        # If no providers exist, we cannot proceed with the migration
        # This should be handled by creating a provider first or raising an error
        return

    # List of models with provider FK that will be altered to NOT NULL
    model_names = [
        'BufferedOrphan', 'Coding', 'Form', 'Interval', 'Query',
        'Record', 'RecordRevision', 'Site', 'Study', 'Subject',
        'SyncJob', 'Variable', 'Visit'
    ]

    for model_name in model_names:
        try:
            Model = apps.get_model('clinical', model_name)
            # Update NULL provider fields to the default provider
            null_count = Model.objects.filter(provider__isnull=True).update(provider=default_provider)
            if null_count > 0:
                logger.info(f"Backfilled {null_count} NULL provider(s) in {model_name}")
        except Exception as e:
            logger.warning(f"Warning: Could not backfill {model_name}: {e}")


def reverse_backfill_null_providers(apps, schema_editor):
    """Reverse function - no-op as we cannot safely restore NULLs."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0013_study_pii_masking_enabled"),
    ]

    operations = [
        # Backfill NULL providers before altering fields to NOT NULL
        migrations.RunPython(backfill_null_providers, reverse_backfill_null_providers),
        migrations.AlterField(
            model_name="bufferedorphan",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="clinical.provider"
            ),
        ),
        migrations.AlterField(
            model_name="coding",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="clinical.provider"
            ),
        ),
        migrations.AlterField(
            model_name="form",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="clinical.provider"
            ),
        ),
        migrations.AlterField(
            model_name="interval",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="clinical.provider"
            ),
        ),
        migrations.AlterField(
            model_name="query",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="clinical.provider"
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="clinical.provider"
            ),
        ),
        migrations.AlterField(
            model_name="recordrevision",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="clinical.provider"
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="clinical.provider"
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="clinical.provider"
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="clinical.provider"
            ),
        ),
        migrations.AlterField(
            model_name="syncjob",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="clinical.provider"
            ),
        ),
        migrations.AlterField(
            model_name="variable",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="clinical.provider"
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="clinical.provider"
            ),
        ),
    ]
