# Generated by Django 5.1.15 on 2026-06-02 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0013_study_pii_masking_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="syncjob",
            name="site_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="syncjob",
            name="study_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
