# Generated by Django 5.1.15 on 2026-06-12 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0015_merge_20260602_1328"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="study",
            options={"permissions": [("view_pii", "Can view unmasked PII")]},
        ),
        migrations.RemoveConstraint(
            model_name="study",
            name="clinical_study_unique_provider_external_id",
        ),
        migrations.AddField(
            model_name="syncjob",
            name="file_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="synctask",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("BUFFERED", "Buffered"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=50,
            ),
        ),
    ]
