# Generated by Django 5.1.15 on 2026-06-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0016_alter_study_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="metadata_mapping",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Maps hierarchical relationships and tags into flattened metadata.",
            ),
        ),
    ]
