# Generated by Django 5.1.15 on 2026-06-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0016_alter_study_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportjob",
            name="contains_phi",
            field=models.BooleanField(default=False),
        ),
    ]
