# Generated by Django 5.1.15 on 2026-06-16 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0017_exportjob_contains_phi"),
        ("clinical", "0017_provider_metadata_mapping"),
    ]

    operations = []
