# Generated by Django 5.1.15 on 2026-06-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0017_exportjob_contains_phi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="syncjob",
            name="file_path",
            field=models.CharField(
                blank=True,
                help_text="Relative path in the storage adapter for bulk ingestion payloads (>2000 entities), set upon upload.",
                max_length=500,
                null=True,
            ),
        ),
    ]
