# Generated by Django 5.1.15 on 2026-06-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinical", "0018_alter_syncjob_file_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="syncjob",
            name="contains_phi",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if this job contains Protected Health Information (PHI).",
            ),
        ),
        migrations.AddField(
            model_name="synctask",
            name="contains_phi",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if this task contains Protected Health Information (PHI).",
            ),
        ),
    ]
