# Generated by Django 5.1.15 on 2026-06-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0019_syncjob_contains_phi_synctask_contains_phi"),
    ]

    operations = [
        migrations.AddField(
            model_name="bufferedorphan",
            name="contains_phi",
            field=models.BooleanField(default=False),
        ),
    ]
