# Generated by Django 5.1.15 on 2026-07-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinical", "0020_bufferedorphan_contains_phi"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="record_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="subject",
            name="date_of_birth",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="subject",
            name="status",
            field=models.CharField(db_index=True, default="active", max_length=50),
        ),
    ]
