# Generated by Django 5.1.15 on 2026-05-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATE", "Create"),
                    ("UPDATE", "Update"),
                    ("DELETE", "Delete"),
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                    ("SECURITY", "Security"),
                    ("UNAUTH", "Unauth"),
                ],
                max_length=10,
            ),
        ),
    ]
