# Generated by Django 5.1.15 on 2026-06-12 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0003_auditlog_study"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="agent_did",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="cryptographic_signature",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="external_transaction_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="supervisor_did",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
